blank_issues_enabled: false
contact_links:
  - name: Правила участия
    url: https://github.com/HutWa/ansys-fluent-russian/blob/main/docs/CONTRIBUTING.md
    about: Перед созданием задачи ознакомьтесь с правилами проекта.
